#Configuracion de Factura - POS JJ
#Mon Jun 01 05:03:04 GMT-05:00 2026
empresa_direccion=AV8\#123
empresa_mensaje=Muchas gracias por su compra, vuelva pronto\!
empresa_nit=1234POSJJ
empresa_nombre=POS JJ
empresa_telefono=31002001904
